# Generated by Django 2.1.4 on 2019-01-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='street_name',
        ),
        migrations.AddField(
            model_name='address',
            name='building',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='street_type',
            field=models.CharField(choices=[('улица', 'ул'), ('переулок', 'пер'), ('проезд', 'пр'), ('бульвар', 'бул'), ('площадь', 'пл'), ('тракт', 'тр'), ('шоссе', 'шс')], default='улица', max_length=30),
        ),
    ]
