# Generated by Django 2.1.5 on 2019-01-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190110_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'адрес', 'verbose_name_plural': 'адреса'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'опция', 'verbose_name_plural': 'опции'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'параметр', 'verbose_name_plural': 'параметры'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'телефон', 'verbose_name_plural': 'телефоны'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'тип товаров', 'verbose_name_plural': 'типы товаров'},
        ),
        migrations.AlterField(
            model_name='address',
            name='area',
            field=models.CharField(max_length=50, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(default='', max_length=10, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='address',
            name='entrance',
            field=models.PositiveSmallIntegerField(verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='address',
            name='flat',
            field=models.PositiveIntegerField(verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.PositiveSmallIntegerField(verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(max_length=20, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='address',
            name='index',
            field=models.PositiveIntegerField(verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_name',
            field=models.CharField(max_length=50, verbose_name='Название улицы'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_type',
            field=models.CharField(choices=[('ул', 'улица'), ('пер', 'переулок'), ('пр', 'проезд'), ('бул', 'бульвар'), ('пл', 'площадь'), ('тр', 'тракт'), ('шс', 'шоссе')], default='ул', max_length=30, verbose_name='Тип улицы'),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='option',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Parameter', verbose_name='Параметр'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=30, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.TextField(default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(to='app.Option', verbose_name='Опции'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProductType', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='parameters',
            field=models.ManyToManyField(to='app.Parameter', verbose_name='Параметры'),
        ),
    ]
