# Generated by Django 2.1.5 on 2019-01-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190123_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
    ]
