# Generated by Django 2.1.4 on 2018-12-30 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Order'),
            preserve_default=False,
        ),
    ]
