# Generated by Django 2.1.5 on 2019-01-23 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190118_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(default='', max_length=50, verbose_name='Время доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время заказа'),
            preserve_default=False,
        ),
    ]
