# Generated by Django 2.1.5 on 2019-01-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190123_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='additional_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Дополнительный телефон'),
        ),
        migrations.AddField(
            model_name='customer',
            name='main_phone',
            field=models.CharField(db_index=True, default='', max_length=30, verbose_name='Главный телефон'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
