# Generated by Django 2.1.5 on 2019-01-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190123_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='area',
            field=models.CharField(blank=True, max_length=50, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='address',
            name='index',
            field=models.PositiveIntegerField(blank=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='main_phone',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Телефон'),
        ),
    ]
